### PR TITLE
start workflow on pull requests

### PR DESCRIPTION
**Pull request by jinlinzh**
start workflow on pull requests

### CODE REVIEW

**Comment by v-jizhang** [comment]
@bot kick off test

**Comment by v-jizhang** [comment]
@bot kick off test

**Comment by v-jizhang** [comment]
@bot kick off test again

**Comment by v-jizhang** [comment]
@bot kick off test
Webhook test

**Comment by v-jizhang** [comment]
@bot kick off test
123456

**Comment by v-jizhang** [comment]
@bot kick off test
Commet created

**Comment by jinlinzh** [comment]
@bot kick off test

**Comment by jinlinzh** [comment]
@bot kick off test
Kick off again

**Comment by jinlinzh** [comment]
@bot kick off test
Kick off again

**Pull request merged**
